TP0 Finalizado
ICOMP-UNC/setup-environment-TheRabbitt pull request #2
Opened 2024-03-19 20:47 UTC by TheRabbitt

Complete el Trabajo Practico 0 siguiendo el paso a paso de la clase, donde se realizo la configuracion de cmake para poder linkear librerias estaticas y dinmacas , ademas de la configuracion de los unit-tests. Tambien se realizo la integracion de unity al entorno y con un poco de investigacion propia extra se inlcuyo la parte de github actions.

Nota: 
-Se modifico la version de la github action checkout a su ultima version (actions/checkout@v4). 
-Se realizo la firma de cada commit.

2024-03-19 20:49 UTC, GabrielEValenzuela requested changes
Add missing new lines

2024-03-20 12:26 UTC, merged

2024-03-20 20:15 UTC, GabrielEValenzuela reviewed
Missing new lines!

2024-03-20 20:15 UTC, GabrielEValenzuela commented on .github/workflows/QAWorkflow.yml
> +
Missign new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on include/greetings.h
> +void greetings();
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on lib/libdyn/CMakeLists.txt
> +add_library(${PROJECT_NAME} SHARED ${SOURCES})
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on lib/libdyn/src/shared.c
> +}
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on lib/libsta/CMakeLists.txt
> +add_library(${PROJECT_NAME} STATIC ${SOURCES})
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on lib/libsta/src/static.c
> +}
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on src/greetings.c
> +}
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on src/logic.c
> +}
Missing new line

2024-03-20 20:15 UTC, GabrielEValenzuela commented on tests/unit/test_unit_program.c
> +}
Missing new line

2024-03-21 02:19 UTC, TheRabbitt commented
Profe , puse el boton de mergear y cerrar , pense que se correjia automaticamente lo de las lineas que fatltaban. Tenia que coreejir todo hacer un push y ahi cerrar el pull?